version: '3'
services:

  api_server:
    image: "stormyyd/yet-another-url-shorter"
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "19650:80"

  mongo:
    image: "mongo:3.7-jessie"
    volumes:
      - /data/db:/data/db